FROM lowyard/golang-dev:latest as build
ADD src/copy.go /workspace/
ADD src/svc.go /workspace/
WORKDIR /workspace
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o copy ./copy.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o svc ./svc.go
FROM bash:latest 
COPY --from=build /workspace/copy /usr/local/bin/
COPY --from=build /workspace/svc /usr/local/bin/
