FROM golang:latest as build
RUN go get -v github.com/go-redis/redis
ADD src/monitor.go /workspace/
WORKDIR /workspace
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o monitor .
FROM bash:latest 
COPY --from=build /workspace/monitor /usr/local/bin/
